### ISSUE TITLE
种子删除失败的问题

### ISSUE THREAD

**Issue by LetMeFly666** [LetMeFly666/BYRBT_RyukawaChihiro#3]
# 问题描述

当前的种子删除方式为：

1. 强制重新汇报（Reannounce）
1. 休眠5秒
1. 暂停种子上传
1. 休眠5秒
1. 删除种子并“同时删除本地文件”

但是我发现qBittorrent删除种子时（不论是重新汇报/是否暂停上传），都有一定的概率删除文件失败。

“删除本地文件失败”就会导致不再做种此种子，但是文件“永久”被保留在磁盘上。

过多的“删除本地文件失败”就会导致磁盘剩余空间不足。

# 拟定方案

删除种子前获取种子对应文件的绝对路径，删除种子后不断检测，若超过一定的时间后文件仍然在硬盘上，则调用系统命令强制删除文件(夹)。需注意“对种子是否删除成功的检测”不能影响“客户端删除种子”（不能因为检测时的读文件导致客户端删除文件失败）。

但是这样就导致程序必须在本地运行而不能在另一台机器上远程控制，要么就是程序在其他机器上运行并且在种子客户端机器上运行一个轻量的文件删除服务（emm，这就和直接在本地运行整个程序也差不多了）。

所以决定增加一个配置：是否强制删除本地文件。

**Comment by kahakaha** [comment]
这个问题很莫名其妙，有时候还会出现文件夹里东西都删了，但是剩一个空文件夹
